project:
  type: book
  output-dir: ../docs

book:
  title: "My Study Notes & Guides"
  author: "Marcella Harris"
  date: today
  chapters:
    - index.qmd
    - courseD421.qmd
    - courseC949.qmd
    - courseD493.qmd
    - courseD495.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    highlight-style: nord
    theme:
      light: lux
      dark: darkly
    css: custom_styles.css
    include-after-body:
      - file: ../custom/custom_script.js
    toc: true
    toc-depth: 5
    toc-expand: 2
    toc-title: "Contents"
    toc_float: true
    toc-options:
      smooth-scroll: true
    page-layout: full
    grid:
      body-width: 975px

editor:
  render-on-save: true
