project:
  type: book
  output-dir: ../docs

book:
  title: "My Study Notes & Guides"
  author: "Marcella Harris"
  date: today
  chapters:
    - index.qmd
    - courseD421.qmd
    - courseC949.qmd
    - courseD493.qmd
    - courseD495.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-expand: 3
    theme:
      - lux
      - brand
  pdf:
    documentclass: scrreprt

editor: 
  render-on-save: true

