project:
  type: book
  output-dir: ../docs

book:
  title: "My Study Notes & Guides"
  author: "Marcella Harris"
  date: today
  chapters:
    - index.qmd
    - courseD421.qmd
    - courseC949.qmd
    - courseD493.qmd
    - courseD495.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    toc-expand: 4
    toc-title: "Contents"
    number-sections: true
    number-depth: 3
    smooth-scroll: true
  pdf:
    documentclass: scrreprt

editor: 
  render-on-save: true

