# Discrete Math II {.unnumbered}

::: {.lead}

Discrete Math II Functions and Applications (D421)

:::

---

::: {.callout-note}
These exercises are not mines. They are from this [Quizlet »](https://quizlet.com/explanations/textbook-solutions/discrete-mathematics-and-its-applications-8th-edition-9781259676512)
:::

---

<br>

### Module 1: Working with Sets

::: {.lead}
#### Section 1.2:
:::

::: {.callout-note title="Exercise 1" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 1a
:::

::: {.panel-tabset}

## Step-1

The goal of this exercise is to list all elements of the set

::: {.text-center}
$\{x∣x \text{ is a real number such that } x^2=1\}$
:::

**What is a set?**

## Step-2

A **set** is an unordered collection of objects that satisfy a certain 
property. This property can be expressed mathematically or in a form of a sentence.

## Step-3

Let's identify all real numbers $x$ for which $x^2=1$.

::: {.text-center}
$x^2 = 1 ⟹ x = ± 1 ⟹ x = ± 1$
:::

Therefore, elements of the given set are $−1$ and $1$. We can also write this as

::: {.text-center}
$\{x∣x \text{ is a real number such that } x^2=1\} = \{-1, 1\}$.
:::

## Step-4

Let's recap what we have done.

We determined that the real numbers whose square is equal to $1$ are $−1$ and $1$, 
and that they are the only elements of this set.

## Results

::: {.text-center}
$−1,1$
:::

:::


::: {.lead}
###### Exercise 1b
:::

::: {.panel-tabset}

## Step-1

In this exercise, we determine whether the given statement represents a proposition.

**What is a proposition?**

## Step-2

A **proposition** is a statement that is known to be true or known to be false. 
If we don't know if a statement is true or false, then the statement is not a 
proposition.

## Step-3

(b)

The statement is a proposition because we know that the statement is false $F$ *(as Tallahassee is the capital of Florida)*.

## Step-4

Let us summarize how the results were derived.

To determine whether a statement is a proposition, we determined whether the 
statement was true or false.

  - If we were able to derive a truth value, then the statement has to be a proposition.
  - If we were unable to assign a truth value to the statement or the truth value was dependent on some variable, then the statement couldn't be a proposition.

## Results

*(b) Proposition, $F$*

:::


::: {.lead}
###### Exercise 1c
:::

::: {.panel-tabset}

## Step-1

In this exercise, we determine whether the given statement represents a proposition.

**What is a proposition?**

## Step-2

A **proposition** is a statement that is known to be true or known to be false. 
If we don't know if a statement is true or false, then the statement is not 
a proposition.

## Step-3

**(c)**

The statement is a proposition because we know that the statement is true 
$T$ *(since 2 added to 3 is equal to 5)*.

## Step-4

Let us summarize how the results were derived.

To determine whether a statement is a proposition, we determined whether the 
statement was true or false.

  - If we were able to derive a truth value, then the statement has to be a proposition.
  - If we were unable to assign a truth value to the statement or the truth value was dependent on some variable, then the statement couldn't be a proposition.

## Results

*(c) Proposition, $T$*

:::


::: {.lead}
###### Exercise 1d
:::

::: {.panel-tabset}

## Step-1

In this exercise, we determine whether the given statement represents a proposition.

**What is a proposition?**

## Step-2

A **proposition** is a statement that is known to be true or known to be false. 
If we don't know if a statement is true or false, then the statement is not 
a proposition.

## Step-3

**(d)**

The statement is a proposition because we know that the statement is false $F$ 
*(since 5 added to 7 is equal to 12, and thus not equal to 10)*.

## Step-4

Let us summarize how the results were derived.

To determine whether a statement is a proposition, we determined whether the 
statement was true or false.

  - If we were able to derive a truth value, then the statement has to be a proposition.
  - If we were unable to assign a truth value to the statement or the truth value was dependent on some variable, then the statement couldn't be a proposition.

## Results

*(d) Proposition, $F$*

:::


::: {.lead}
###### Exercise 1e 
:::

::: {.panel-tabset}

## Step-1

In this exercise, we determine whether the given statement represents a proposition.

**What is a proposition?**

## Step-2

A **proposition** is a statement that is known to be true or known to be false. 
If we don't know if a statement is true or false, then the statement is not 
a proposition.

## Step-3

**(e)**

The statement is not a proposition, because the statement could be true or could be **false** *(but we do not know which case since $x$ is unknown)*.

## Step-4

Let us summarize how the results were derived.

To determine whether a statement is a proposition, we determined whether the 
statement was true or false.

  - If we were able to derive a truth value, then the statement has to be a proposition.
  - If we were unable to assign a truth value to the statement or the truth value was dependent on some variable, then the statement couldn't be a proposition.

## Results

*(e) Not a proposition*

:::


::: {.lead}
###### Exercise 1f
:::

::: {.panel-tabset}

## Step-1

In this exercise, we determine whether the given statement represents a proposition.

**What is a proposition?**

## Step-2

A **proposition** is a statement that is known to be true or known to be false. If we don't know if a statement is true or false, then the statement is not a proposition.

## Step-3

**(f)**

The statement is not a proposition, because it is not a statement that could be true or false.

## Step-4

Let us summarize how the results were derived.

To determine whether a statement is a proposition, we determined whether the statement was true or false.

  - If we were able to derive a truth value, then the statement has to be a proposition.
  - If we were unable to assign a truth value to the statement or the truth value was dependent on some variable, then the statement couldn't be a proposition.

## Results

*(f) Not a proposition*

:::

:::

::: {.callout-note title="Exercise 2" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 2a
:::

::: {.panel-tabset}

## Step-1

**PART A:** This sentence is not a proposition because it is not a declarative sentence. 

So it is not possible for this sentence to be true or false.

## Step-2

PART A: not a proposition

:::


::: {.lead}
###### Exercise 2b
:::

::: {.panel-tabset}

## Step-1

*PART B:* This sentence is not a proposition because it is not a declarative sentence. 

So it is not possible for this sentence to be true or false.

## Step-2

*PART B: not a proposition*

:::


::: {.lead}
###### Exercise 2c
:::

::: {.panel-tabset}

## Step-1

**PART C:** This sentence is a proposition because it can either be true or false. 

Its truth value is false because black flies exist everywhere.


## Step-2

*PART C: proposition, false*

:::


::: {.lead}
###### Exercise 2d
:::

::: {.panel-tabset}

## Step-1

**PART D:** This sentence is not a proposition because the value of $x$ is not given. 

So it is not possible for this sentence to be true or false.

## Step-2

*PART D: not a proposition*

:::

::: {.lead}
###### Exercise 2e
:::

::: {.panel-tabset}
## Step-1

**PART E:** This sentence is a proposition because it can either be true or false. 

Its truth value is false because the moon is not made from green cheese.


## Step-2

*PART E: proposition, false*

:::

::: {.lead}
###### Exercise 2f
:::

::: {.panel-tabset}

## Step-1

PART F: This sentence is not a proposition because the value of $n$ is not given. 

So it is not possible for this sentence to be true or false.

## Step-2

*PART F: not a proposition*

:::

:::

::: {.callout-note title="Exercise 3" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 3 
:::

::: {.panel-tabset}

## Step-1

**(a)**

::: {.text-center}
$\text{ Linda is younger than Sanjay. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Linda is not younger than Sanjay. }$
:::

*Note: This sentence is also equivalent with: Linda is older or the same age as Sanjay.*


## Step-2

**(b)**

::: {.text-center}
$\text{ Mei makes more money than Isabella. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Mei does not make more money than Isabella. }$
:::

*Note: This sentence is also equivalent with: Mei makes less money or the same amount of money than Isabella.*

## Step-3

**(c)**

::: {.text-center}
$\text{ Moshe is taller than Monica. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Moshe is not taller than Monica. }$
:::

*Note: This sentence is also equivalent with: Moshe is shorter or the same height as Monica.*

## Step-4

**(d)**

::: {.text-center}
$\text{ Abby is richer than Ricardo. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Abby is not richer than Ricardo. }$
:::

*Note: This sentence is also equivalent with: Abby is poorer or equally rich to Ricardo.*

## Results

::: {.text-center}
**(a)** Linda is not younger than Sanjay.

**(b)** Mei does not make more money than Isabella.

**(c)** Moshe is not taller than Monica.

**(d)** Abby is not richer than Ricardo.
:::

:::

:::

::: {.callout-note title="Exercise 4" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 4a
:::

::: {.panel-tabset}

## Step-1

**(a)**

::: {.text-center}
$\text{ Janice has more Facebook friends than Juan. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Janice does not have more Facebook friends than Juan. }$
:::

*Note: This sentence is also equivalent with: Janice has less Facebook friends or the same number of Facebook friends as Juan.*


## Step-2

**(b)** 

::: {.text-center}
$\text{ Quincy is smarter than Venkat. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Quincy is not smarter than Venkat. }$
:::

*Note: This sentence is also equivalent with: Quincy is dumber or equally intelligent as Venkat.*

## Step-3

**(c)**

::: {.text-center}
$\text{ Zelda drives more miles to school than Paola. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Zelda does not drive more miles to school than Paola. }$
:::

*Note: This sentence is also equivalent with: Zelda drives less miles or the same number of miles to school than Paola.*

## Step-4

**(d)**

::: {.text-center}
$\text{ Brianna sleeps longer than Gloria. }$
:::

The negation of the proposition adds the word "not" to the sentence:

::: {.text-center}
$\text{ Brianna does not sleep longer than Gloria. }$
:::

*Note: This sentence is also equivalent with: Brianna sleeps less or the same amount than Gloria.*

#### Results

::: {.text-center}
**(a)** Janice does not have more Facebook friends than Juan.

**(b)** Quincy is not smarter than Venkat.

**(c)** Zelda does not drive more miles to school than Paola.

**(d)** Brianna does not sleep longer than Gloria.
:::

:::

:::

::: {.callout-note title="Exercise 5" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 5a
:::

::: {.panel-tabset}

## Step-1

**DEFINITIONS**

The negation of a statement states the opposite of the given statement.

## Step-2

**SOLUTION**

**(a)** The opposite of a statement can be obtained by adding "not" to the given statement. The opposite of Mei having an MP3 player is that Mei does not have an MP3 player.

## Step-3

*(a) Mei does not have an MP3 player.*

:::


::: {.lead}
###### Exercise 5b
:::

::: {.panel-tabset}

## Step-1

**DEFINITIONS**

The negation of a statement states the opposite of the given statement.

## Step-2

**SOLUTION**

**(b)** The opposite of no pollution in New Jersey is that there is pollution in New Jersey.

## Step-3

*(b) There is pollution in New Jersey.*

:::


::: {.lead}
###### Exercise 5c
:::

::: {.panel-tabset}

## Step-1

**DEFINITIONS**

The negation of a statement states the opposite of the given statement.

## Step-2

**SOLUTION**

**(c)** The opposite of an equality $(=)$ is a difference $\text{(≠)   2+1 ≠ 3 }$

## Step-3

*(c) $2+1 ≠ 3$*

:::


::: {.lead}
###### Exercise 5d
:::

::: {.panel-tabset}

## Step-1

**DEFINITIONS**

The negation of a statement states the opposite of the given statement.

## Step-2

**SOLUTION**

**(d)** The opposite of a statement can be obtained by adding *"not"* to the given statement: The summer in Maine is not *(hot and sunny)*.

## Step-3

*(d) The summer in Maine is not (hot and sunny).*

:::

:::

::: {.callout-note title="Exercise 6" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### *coming soon ...*
:::

:::

::: {.callout-note title="Exercise 7" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 7a
:::

::: {.panel-tabset}

## Step-1

**DEFINITION**

The negation of a statement states the opposite of the given statement.

## Step-2

**(a)** The opposite of a statement can be obtained by adding "not" to the given statement 

*(note: adjust the sentence such that it remains proper English):*
  - Steve does not have more than 100 GB free disk space on his laptop.

## Step-3

*(a) Steve does not have more than 100 GB free disk space on his laptop.*

:::



::: {.lead}
###### Exercise 7b
:::

::: {.panel-tabset}

## Step-1

**DEFINITION**

The negation of a statement states the opposite of the given statement.

## Step-2

**(b)** The opposite of a statement can be obtained by adding "not" to the given statement *(note: adjust the sentence such that it remains proper English):* **Zach does not block e-mails and texts from Jennifer.**

## Results

*(b) Zach does not block e-mails and texts from Jennifer.*

:::

::: {.lead}
###### Exercise 7c
:::

::: {.panel-tabset}

## Step-1

**DEFINITION**

The negation of a statement states the opposite of the given statement.

## Step-2

**(c)** The opposite of an equality $(=)$ is a difference $(≠)$

::: {.text-center}
$\text{7 ⋅ 11 ⋅ 13 ≠ 999}$
:::

## Results

::: {.text-center}
$\text{7 ⋅ 11 ⋅ 13 / 999}$
:::

:::


::: {.lead}
###### Exercise 7d
:::

::: {.panel-tabset}

## Step-1

**DEFINITION**

The negation of a statement states the opposite of the given statement.

## Step-2

**(d)** The opposite of a statement can be obtained by adding "not" to the given statement *(note: adjust the sentence such that it remains proper English):* **Diane did not ride her bicycle 100 miles on Sunday.**

## Results

::: {.text-center}
*(d) Diane did not ride her bicycle 100 miles on Sunday.*
:::

:::

:::

::: {.callout-note title="Exercise 8" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 8a
:::

::: {.panel-tabset}

## Step-1

**A. ** Smartphone B has 288 MB RAM, which is the most out of the other two phones.

## Results

::: {.text-center}
*A. True*
:::

:::


::: {.lead}
###### Exercise 8b
:::

::: {.panel-tabset}

## Step-1

**B. ** Either the ROM has to be greater or the resolution has to be greater. The resolution is greater in this example so it is true.

## Results

::: {.text-center}
*B. True*
:::

:::


::: {.lead}
###### Exercise 8c
:::

::: {.panel-tabset}

## Step-1

**C. ** It is false because the resolution is larger in Smartphone A.

## Results

::: {.text-center}
*C. False*
:::

:::


::: {.lead}
###### Exercise 8d
:::

::: {.panel-tabset}

## Step-1

**D. ** It may have more RAM and ROM, but Smartphone B's resolution is less making the statement false.

## Results

::: {.text-center}
*D. False*
:::

:::


::: {.lead}
###### Exercise 8e
:::

::: {.panel-tabset}
## Step-1

**E. ** It is a biconditional statement which is F - T making the statement false.

## Results

::: {.text-center}
*E. False*
:::

:::

:::

::: {.callout-note title="Exercise 9" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 9a
:::

::: {.panel-tabset}

## Step-1

**a.** This proposition is false because Quixote Media had less annual revenue than Acme Computer ($111 billion < $138 billion).

## Results

::: {.text-center}
*a. False*
:::

:::


::: {.lead}
###### Exercise 9b
:::

::: {.panel-tabset}

## Step-1

**b. ** This proposition is true because both statements are true.

## Results

::: {.text-center}
*b. True*
:::

:::


::: {.lead}
###### Exercise 9c
:::

::: {.panel-tabset}

## Step-1

**c. ** This proposition is true because Quixote Media had the largest net profit. 

*Note: Since this is an $V$ statement, either statement being true makes the proposition true.*

## Results

::: {.text-center}
*c. True*
:::

:::


::: {.lead}
###### Exercise 9d
:::

::: {.panel-tabset}

## Step-1

**d. ** This proposition is true because Acme Computer had the largest revenue.

*Note: this is an $⇒$ proposition. Even though Quixote did not have the smallest net profit (hypothesis), the conclusion still holds.*

## Results

::: {.text-center}
*d. True*
:::

:::


::: {.lead}
###### Exercise 9e
:::

::: {.panel-tabset}
## Step-1

**e. ** This proposition is true because in both directions the conclusions hold true.

## Results

::: {.text-center}
*e. True*
:::

:::

:::

::: {.callout-note title="Exercise 10" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 10a
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(a) I did not buy a lottery ticket this week.
:::

## Results

::: {.text-center}
*(a) I did not buy a lottery ticket this week.*
:::

:::


::: {.lead}
###### Exercise 10b
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(b) I bought a lottery ticket this week or I won the million dollar jackpot.
:::

## Results

::: {.text-center}
*(b) I bought a lottery ticket this week or I won the million-dollar jackpot.*
:::

:::


::: {.lead}
###### Exercise 10c
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(c) If I bought a lottery ticket this week, then I won the million dollar jackpot.
:::

## Results

::: {.text-center}
*(c) If I bought a lottery ticket this week, then I won the million-dollar jackpot.*
:::

:::


::: {.lead}
###### Exercise 10d
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(d) I bought a lottery ticket this week and I won the million dollar jackpot.
:::

## Results

::: {.text-center}
*(d) I bought a lottery ticket this week and I won the million-dollar jackpot.*
:::

:::


::: {.lead}
###### Exercise 10e
:::

::: {.panel-tabset}
## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(e) I bought a lottery ticket this week if and only if I won the million dollar jackpot.
:::

## Results

::: {.text-center}
*(e) I bought a lottery ticket this week if and only if I won the million-dollar jackpot.*
:::

:::


::: {.lead}
###### Exercise 10f
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(f) If I did not buy a lottery ticket this week, then I did not win the million dollar jackpot.
:::

## Results

::: {.text-center}
*(f) If I did not buy a lottery ticket this week, then I did not win the million-dollar jackpot.*
:::

:::


::: {.lead}
###### Exercise 10g
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(g) I did not buy a lottery ticket this week and I did not win the million dollar jackpot.
:::

## Results

::: {.text-center}
*(g) I did not buy a lottery ticket this week and I did not win the million dollar jackpot.*
:::

:::


::: {.lead}
###### Exercise 10h
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p:* I bought a lottery ticket this weekend.

*q:* I won the million-dollar jackpot.
:::

**Interpretation Symbols**

::: {.text-center}
$¬p: \text{not p}$

$p ∨ q: \text{p or q}$

$p ∧ q: \text{p and q}$

$p → q: \text{if p, then q}$

$p ↔ q: \text{p if and only if q}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(h) I did not buy a lottery ticket this week and I did not win the million dollar jackpot.
:::

## Results

::: {.text-center}
*(h) I did not buy a lottery ticket this week or, I bought a lottery ticket this week and won the million dollar jackpot.*
:::

:::

:::

::: {.callout-note title="Exercise 11" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 11a
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(a) Sharks have not been spotted near the shore.
:::

## Result

::: {.text-center}
*(a) Sharks have not been spotted near the shore.*
:::

:::

<br>

::: {.lead}
###### Exercise 11b
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(b) Swimming at the New Jersey shore is allowed and sharks have been spotted near the shore.
:::

## Result

::: {.text-center}
*(b) Swimming at the New Jersey shore is allowed and sharks have not been spotted near the shore.*
:::

:::

<br>

::: {.lead}
###### Exercise 11c
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(c) Swimming at the New Jersey shore is not allowed or sharks have been spotted near the shore.
:::

## Result

::: {.text-center}
*(c) Swimming at the New Jersey shore is not allowed or sharks have been spotted near the shore.*
:::

:::

<br>

::: {.lead}
###### Exercise 11d
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(d) If swimming at the New Jersey shore is allowed, then sharks have not been spotted near the shore.
:::

## Result

::: {.text-center}
*(d) If swimming at the New Jersey shore is allowed, then sharks have not been spotted near the shore.*
:::

:::

<br>

::: {.lead}
###### Exercise 11e
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(e) If sharks have not been spotted near the shore, then swimming at the New Jersey Shore is allowed.
:::

## Result

::: {.text-center}
*(e) If sharks have not been spotted near the shore, then swimming at the New Jersey Shore is allowed.*
:::

:::

<br>

::: {.lead}
###### Exercise 11f
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(f) If swimming at the New Jersey shore is not allowed, then sharks have not been spotted near the shore.
:::

## Result

::: {.text-center}
*(f) If swimming at the New Jersey shore is not allowed, then sharks have not been spotted near the shore.*
:::

:::

<br>

::: {.lead}
###### Exercise 11g
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(g) Swimming at the New Jersey shore is allowed if and only if sharks have not been spotted near the shore.
:::

## Result

::: {.text-center}
*(g) Swimming at the New Jersey shore is allowed if and only if sharks have not been spotted near the shore.*
:::

:::

<br>

::: {.lead}
###### Exercise 11h
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: Swimming at the New Jersey shore is allowed.*

*q: Sharks have been spotted near the shore.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(h) Swimming at the New Jersey shore is not allowed and, swimming at the New Jersey shore is either allowed or sharks have not been spotted near the shore.
:::

*Note: The word "either" replaced the parentheses in the given proposition.*

## Result

::: {.text-center}
*(h) Swimming at the New Jersey shore is not allowed and, either swimming at the New Jersey shore is allowed or sharks have not been spotted near the shore.*
:::

:::

:::

::: {.callout-note title="Exercise 12" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 12a
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
*p: The election is decided.*

*q: The votes have been counted.*
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(a) The election is not decided.
:::

## Result

::: {.text-center}
*(a) The election is not decided.*
:::

:::

<br>

::: {.lead}
###### Exercise 12b
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: The election is decided.

q: The votes have been counted.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(b) The election is decided or the votes have been counted.
:::

## Result

::: {.text-center}
*(b) The election is decided or the votes have been counted.*
:::

:::

<br>

::: {.lead}
###### Exercise 12c
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: The election is decided.

q: The votes have been counted.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(c) The election is not decided and the votes have been counted.
:::

## Result

::: {.text-center}
*(c) The election is not decided and the votes have been counted.*
:::

:::

<br>

::: {.lead}
###### Exercise 12d
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: The election is decided.

q: The votes have been counted.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(d) If the votes have been counted, then the election is decided.
:::

## Result

::: {.text-center}
*(d) If the votes have been counted, then the election is decided.*
:::

:::

<br>

::: {.lead}
###### Sub-Title
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: The election is decided.

q: The votes have been counted.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(e) If the votes have not been counted, then the election is not decided.
:::

## Result

::: {.text-center}
*(e) If the votes have not been counted, then the election is not decided.*
:::

:::

<br>

::: {.lead}
###### Exercise 12f
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: The election is decided.

q: The votes have been counted.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(f) If the election is not decided, then the votes have not been counted.
:::

## Result

::: {.text-center}
*(f) If the election is not decided, then the votes have not been counted.*
:::

:::

<br>

::: {.lead}
###### Exercise 12g
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: The election is decided.

q: The votes have been counted.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(g) The election is decided if and only if the votes have been counted.
:::

## Result

::: {.text-center}
*(g) The election is decided if and only if the votes have been counted.*
:::

:::

<br>

::: {.lead}
###### Exercise 12h
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: The election is decided.

q: The votes have been counted.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(h) The votes have not been counted or, the election is not decided and the votes have been counted.
:::

*Note: We replace the brackets by a comma "," in between the statement (to represent the brackets).*

## Result

::: {.text-center}
*(h) The votes have not been counted or, the election is not decided and the votes have been counted.*
:::

:::

:::

::: {.callout-note title="Exercise 13" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 13 a
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: It is below freezing.

q: It is snowing.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(a) The given proposition states: $\text{p and q}$, or equivalently $p∧q$.
:::

## Result

::: {.text-center}
*(a) $p∧q$ *
:::

:::

::: {.lead}
###### Exercise 13b
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: It is below freezing.

q: It is snowing.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(b) The given proposition states: $\text{p and not q}$, or equivalently $p∧¬q$.
:::

## Result

::: {.text-center}
*(b) $p∧¬q$*
:::

:::

::: {.lead}
###### Exercise 13c
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: It is below freezing.

q: It is snowing.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(c) The given proposition states: $\text{not p and not q}$, or equivalently $¬p∧¬q$.
:::

## Result

::: {.text-center}
*(c) $¬p∧¬q$*
:::

:::

::: {.lead}
###### Exercise 13d
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: It is below freezing.

q: It is snowing.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(d) The given proposition states: $\text{p or q}$, or equivalently $p∨q$.
:::

## Result

::: {.text-center}
*(d) $p∨q$*
:::

:::

::: {.lead}
###### Exercise 13e
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: It is below freezing.

q: It is snowing.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(e) The given proposition states: $\text{if p, then q}$, or equivalently $p→q$.
:::

## Result

::: {.text-center}
*(e) $p→q$*
:::

:::

::: {.lead}
###### Exercise 13f
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: It is below freezing.

q: It is snowing.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(f) The given proposition states: $\text{p or q, and if p then not q}$, or equivalently $(p∨q)∧(p→¬q)$.
:::

## Result

::: {.text-center}
*(f) $(p∨q)∧(p→¬q)$*
:::

:::

::: {.lead}
###### Exercise 13g
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: It is below freezing.

q: It is snowing.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Determine the English sentences by replacing $\text{p and q}$ by their given sentences 
in the above interpretations *(and adjust the sentence to form a proper English sentence as needed):*

::: {.text-center}
(g) *"Necessary and sufficient"* means the same as *"if and only if"*. 
The given proposition then states: $\text{p if and only if q}$, or equivalently $p↔q$.
:::

## Result

::: {.text-center}
*(g) $p↔q$*
:::

:::

<!-- end of collapse -->
::: 

::: {.callout-note title="Exercise 14" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
Exercise 14a
:::

::: {.panel-tabset}

## Ex. A

(A.) If you have the flu, then you will miss the final examination.

::: {.text-center}
Conditional Statement
:::

## Ex. B

(B.) If you won’t miss the final examination, then you’ll pass the course, 
and conversely.

::: {.text-center}
Biconditional Statement.
:::

## Ex. C

(C.) If you miss the final examination, then you will not pass the course

::: {.text-center}
Conditional Statement and negate r
:::

## Ex. D

(D.) You have the flu, or you miss the final examination, or you pass the course.

::: {.text-center}
All are disjunctions so use or
:::

## Ex. E

(E.) If you have the flu, then you will not pass the course or if you miss the 
final examination, you will not pass the course.

::: {.text-center}
*(Conditional statement of p and negation of r)* Disjunction *(Conditional Statement of q and negation of r)*
:::

## Ex. F

(F.) You have the flu and you miss the final examination or you don’t miss the 
final examination and you pass the course.

::: {.text-center}
(P conjunction of Q) Disjunction (negation of Q conjunction of R)
:::

:::


::: {.lead}
Exercise 14b
:::

::: {.panel-tabset}

## Ex. A

(B)> You won't miss the final examination if and only if you pass the course.

::: {.text-center}
Bi-conditional statement
:::

## Result

::: {.text-center}
(B) You won't miss the final examination if and only if you pass the course.
:::

:::


::: {.lead}
Exercise 14c
:::

::: {.panel-tabset}

## Ex. A

(C) If you miss the examination then you will be failing the course

::: {.text-center}
Implication Statement
:::

:::


::: {.lead}
Exercise 14d
:::

::: {.panel-tabset}

## Ex. A

(D) You have the flu OR you miss the final examination OR you pass the course.

::: {.text-center}
Disjunction Proposition
:::

:::


::: {.lead}
Exercise 14e
:::

::: {.panel-tabset}

## Ex. A

(E) If you have the flu then you'll not pass the course OR If you miss the final 
examination then you'll fail the course

::: {.text-center}
(P implies not R) OR (Q implies not R)
:::

:::


::: {.lead}
Exercise 14f
:::

::: {.panel-tabset}

## Ex. A

(F) You have the flu and you miss the examination OR You will not miss the 
final examination and you pass the course

::: {.text-center}
(P and Q) OR (not Q and R)
:::

:::

<!-- end of collapse -->
:::

::: {.callout-note title="Exercise 15" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 15a
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: You drive over 65 miles per hour.

q:You get a speeding ticket.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Replace the propositions of $\text{p and q}$ by their symbol in the given propositions, 
then use the above interpretation of the symbols.

::: {.text-center}
(a) The given proposition states: $\text{not p}$, or equivalently $¬p$.
:::

## Result

::: {.text-center}
*(a) $¬p$*
:::

:::

::: {.lead}
###### Exercise 15b
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: You drive over 65 miles per hour.

q:You get a speeding ticket.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Replace the propositions of $\text{p and q}$ by their symbol in the given propositions, 
then use the above interpretation of the symbols.

::: {.text-center}
(b) The given proposition states: $\text{p and not q}$, or equivalently $p∧¬q$.
:::

## Result

::: {.text-center}
*(b) $p∧¬q$*
:::

:::

::: {.lead}
###### Exercise 15c
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: You drive over 65 miles per hour.

q:You get a speeding ticket.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Replace the propositions of $\text{p and q}$ by their symbol in the given propositions, 
then use the above interpretation of the symbols.

::: {.text-center}
(c) The given proposition states: $\text{if p then q}$, or equivalently $p→q$.
:::

## Result

::: {.text-center}
*(c) $p→q$*
:::

:::

::: {.lead}
###### Exercise 15d
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: You drive over 65 miles per hour.

q:You get a speeding ticket.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Replace the propositions of $\text{p and q}$ by their symbol in the given propositions, 
then use the above interpretation of the symbols.

::: {.text-center}
(d) The given proposition states: $\text{if not p then not q}$, or equivalently $¬p→¬q$.
:::

## Result

::: {.text-center}
*(d) $¬p→¬q$*
:::

:::

::: {.lead}
###### Exercise 15e
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: You drive over 65 miles per hour.

q:You get a speeding ticket.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Replace the propositions of $\text{p and q}$ by their symbol in the given propositions, 
then use the above interpretation of the symbols.

::: {.text-center}
(e) "Sufficient" means the same as the if-then statement. The given proposition 
states: $\text{if p, then q}$, or equivalently $p→q$.
:::

## Result

::: {.text-center}
*(e) $p→q$*
:::

:::

::: {.lead}
###### Exercise 15f
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: You drive over 65 miles per hour.

q:You get a speeding ticket.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Replace the propositions of $\text{p and q}$ by their symbol in the given propositions, 
then use the above interpretation of the symbols.

::: {.text-center}
(f) The given proposition states: $\text{q and not p}$, or equivalently $q∧¬p$.
:::

## Result

::: {.text-center}
*(f) $q∧¬p$*
:::

:::

::: {.lead}
###### Exercise 15g
:::

::: {.panel-tabset}

## Step-1

**Given:**

::: {.text-center}
**
p: You drive over 65 miles per hour.

q:You get a speeding ticket.
**
:::

**Interpretation Symbols**

::: {.text-center}
$\text{¬p: not p}$

$\text{p∨q: p or q}$

$\text{p∧q: p and q}$

$\text{p→q: if p, then}$ 

$\text{p↔q: if and only if}$
:::

## Step-2

**SOLUTION**

Replace the propositions of $\text{p and q}$ by their symbol in the given propositions, 
then use the above interpretation of the symbols.

::: {.text-center}
(g) We could rewrite the given sentence as: If you get a speeding ticket, then you are driving are 65 miles per hour. The given proposition then states: $\text{if q then p}$, or equivalently $q→p.$
:::

## Result

::: {.text-center}
*(g) $q→p$*
:::

:::

<!-- end of collapse -->
:::

::: {.callout-note title="Exercise 16" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 16a
:::

::: {.panel-tabset}

## Step-1

We are given the three propositions (note that they are declarative and thus propositions indeed):

::: {.text-center}
$\text{p: You get an A on the final exam,}$

$\text{q: You do every exercise in this book,}$

$\text{r: You get an A in this class.}$
:::

## Step-2

a. The conjunction "but" essentially logically corresponds to "and" since it 
implies that two statements are simultaneously true.

The first part of statement corresponds directly to proposition $r$ and the 
second *(after comma)* to negation of the proposition $q$, yielding:

::: {.text-center}
$r∧¬q$
:::

## Result

::: {.text-center}
*a. $r∧¬q$*
:::

:::

::: {.lead}
###### Exercise 16b
:::

::: {.panel-tabset}

## Step-1

We are given the three propositions (note that they are declarative and thus propositions indeed):

::: {.text-center}
$\text{p: You get an A on the final exam,}$

$\text{q: You do every exercise in this book,}$

$\text{r: You get an A in this class.}$
:::

## Step-2

**b.** There are essentially three distinct statements in given sentence, each 
corresponding to one of the given three propositions and thus we write it as:

::: {.text-center}
$p∧q∧r$
:::

## Result

::: {.text-center}
*b. $p∧q∧r$*
:::

:::

::: {.lead}
###### Exercise 16c
:::

::: {.panel-tabset}

## Step-1

We are given the three propositions (note that they are declarative and thus propositions indeed):

::: {.text-center}
$\text{p: You get an A on the final exam,}$

$\text{q: You do every exercise in this book,}$

$\text{r: You get an A in this class.}$
:::

## Step-2

**c.** The first part of the given sentence contains proposition r and the second 
contains proposition $p$. The word *"necessary"* obviously implies necessity, 
precisely the fact that if $r$ is true, $p$ must be true as well:

::: {.text-center}
$r→p$
:::

## Result

::: {.text-center}
*c. $r→p$*
:::

:::

::: {.lead}
###### Exercise 16d
:::

::: {.panel-tabset}

## Step-1

We are given the three propositions (note that they are declarative and thus propositions indeed):

::: {.text-center}
$\text{p: You get an A on the final exam,}$

$\text{q: You do every exercise in this book,}$

$\text{r: You get an A in this class.}$
:::

## Step-2

**d.** The three statements in the given sentence evidently correspond to, in order, 
propositions $p$, $¬q$, and $r$.

As before *"but"* implies the independent nature of the first two, i.e. that 
they are both true $—$ we use the logical conjunction.

Similarly, the word "nevertheless" implies this logical operation as well — the 
statements are true regardless of one another, i.e. simultaneously:

::: {.text-center}
$p∧¬q∧r$
:::

## Result

::: {.text-center}
*d. $p∧¬q∧r$*
:::

:::

::: {.lead}
###### Exercise 16e
:::

::: {.panel-tabset}

## Step-1

We are given the three propositions (note that they are declarative and thus propositions indeed):

::: {.text-center}
$\text{p: You get an A on the final exam,}$

$\text{q: You do every exercise in this book,}$

$\text{r: You get an A in this class.}$
:::

## Step-2

**e.** The part of the sentence before the word "sufficient" is simply the logical 
conjunction of propositions p and q, and the part after it is a proposition r.

The sufficiency of the first part means that it is true and will imply that the 
second part is true as well, or put in mathematical terms:

::: {.text-center}
$(p∧q)→r$
:::

## Result

::: {.text-center}
*e. $(p∧q)→r$*
:::

:::

::: {.lead}
###### Exercise 16f
:::

::: {.panel-tabset}

## Step-1

We are given the three propositions (note that they are declarative and thus propositions indeed):

::: {.text-center}
$\text{p: You get an A on the final exam,}$

$\text{q: You do every exercise in this book,}$

$\text{r: You get an A in this class.}$
:::

## Step-2

**f.** As we know, "if and only if" corresponds to logical equivalence, so we 
only need to write the parts before and after those words in terms of propositions 
and logical operators.

The part before it evidently corresponds to proposition $r$ and the one after is 
a disjunction of statements $\text{p and q}$. Thus, the solution is:

::: {.text-center}
$r↔(p∨q)$
:::

## Result

::: {.text-center}
*f. $r↔(p∨q)$*
:::

:::

<!-- end of collapse -->
:::

::: {.callout-note title="Exercise 17" collapse="true" appearance="simple" icon="false" style="border-left:none; border-right:none; border-top:none; border-bottom:none;"}

::: {.lead}
###### Exercise 17a
:::

::: {.panel-tabset}

## Ex. 1

::: {.text-left}
(A.) $r∧¬p$
:::

::: {.lead}
Conjunction of r and negation of p
:::

## Ex. 2

(B.) $¬p∧q∧r$

::: {.text-center}
Negation of p conjunction of q conjunction of r
:::

## Ex. 3

(C.) $r→(q↔¬p)$

::: {.text-center}
Conditional statement of r and q biconditional of negation of p
:::

## Ex. 4

(D.) $¬q∧¬p∧r$

::: {.text-center}
Negation of q conjunction of negation of p conjunction of r
:::

## Ex. 5

(E.) $(q→(¬r∧p))∧¬((¬r∧¬p)→q)$

::: {.text-center}
A conditional statement of q and negation of r conjunction of p. Conjunction of 
negation *(Negation of r conjunction of negation of p)* conditional of q.
:::

## Ex. 6

(F.) $(p∧r)→¬q$

::: {.text-center}
(Conjunction of p and r) conditional of negation of q
:::

:::

<!-- end of collapse -->
:::
